import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/providers.dart';
import '../../core/constants/app_constants.dart';
import '../../models/models.dart';
class SettingsScreen extends StatelessWidget {
  const SettingsScreen({super.key});
  @override
  Widget build(BuildContext context) { final settings = context.watch<SettingsProvider>(); final goals = context.watch<GoalProvider>(); return Scaffold(appBar: AppBar(title: const Text('Configuración')), body: ListView(children: [_SH(title: 'Apariencia'), ListTile(leading: const Icon(Icons.dark_mode_rounded), title: const Text('Tema'), subtitle: Text(settings.themeMode == ThemeMode.dark ? 'Oscuro' : settings.themeMode == ThemeMode.light ? 'Claro' : 'Sistema'), trailing: DropdownButton<ThemeMode>(value: settings.themeMode, underline: const SizedBox(), items: const [DropdownMenuItem(value: ThemeMode.system, child: Text('Sistema')), DropdownMenuItem(value: ThemeMode.light, child: Text('Claro')), DropdownMenuItem(value: ThemeMode.dark, child: Text('Oscuro'))], onChanged: (v) => settings.setThemeMode(v!))), _SH(title: 'Finanzas'), ListTile(leading: const Icon(Icons.percent_rounded), title: const Text('% ahorro domicilios'), subtitle: Text('${settings.deliveryPercentage.toInt()}% del ingreso')), Padding(padding: const EdgeInsets.symmetric(horizontal: 16), child: Row(children: [const Text('1%', style: TextStyle(fontSize: 12)), Expanded(child: Slider(value: settings.deliveryPercentage, min: 1, max: 50, divisions: 49, activeColor: AppColors.primary, label: '${settings.deliveryPercentage.toInt()}%', onChanged: (v) => settings.setDeliveryPercentage(v))), const Text('50%', style: TextStyle(fontSize: 12))])), _SH(title: 'Notificaciones'), SwitchListTile(secondary: const Icon(Icons.notifications_rounded), title: const Text('Recordatorio diario'), value: settings.dailyReminder, activeColor: AppColors.primary, onChanged: (v) => settings.setDailyReminder(v)), if (settings.dailyReminder) ListTile(leading: const Icon(Icons.access_time_rounded), title: const Text('Hora'), subtitle: Text(settings.reminderTime), trailing: const Icon(Icons.edit_rounded, size: 18), onTap: () => _pickTime(context, settings)), _SH(title: 'Metas'), ...goals.goals.map((g) => _GT(goal: g)), ListTile(leading: Container(padding: const EdgeInsets.all(6), decoration: BoxDecoration(color: AppColors.info.withOpacity(0.15), borderRadius: BorderRadius.circular(8)), child: const Icon(Icons.add_rounded, color: AppColors.info)), title: const Text('Nueva meta'), onTap: () => _goalDialog(context)), _SH(title: 'Acerca de'), const ListTile(leading: Icon(Icons.info_outline_rounded), title: Text('DomiFinance v1.0.0'), subtitle: Text('App financiera · 100% offline · SQLite'))])); }
  Future<void> _pickTime(BuildContext context, SettingsProvider settings) async { final parts = settings.reminderTime.split(':'); final picked = await showTimePicker(context: context, initialTime: TimeOfDay(hour: int.parse(parts[0]), minute: int.parse(parts[1]))); if (picked != null) settings.setReminderTime('${picked.hour.toString().padLeft(2,'0')}:${picked.minute.toString().padLeft(2,'0')}'); }
  void _goalDialog(BuildContext context) { final tc = TextEditingController(); final ac = TextEditingController(); String period = 'diario'; showModalBottomSheet(context: context, isScrollControlled: true, shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))), builder: (ctx) => StatefulBuilder(builder: (ctx, sl) => Padding(padding: EdgeInsets.only(bottom: MediaQuery.of(ctx).viewInsets.bottom, left: 20, right: 20, top: 24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Nueva meta', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 16), TextField(controller: tc, decoration: const InputDecoration(labelText: 'Nombre')), const SizedBox(height: 12), TextField(controller: ac, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Monto objetivo', prefixText: '\$ ')), const SizedBox(height: 12), DropdownButtonFormField<String>(value: period, decoration: const InputDecoration(labelText: 'Período'), items: const [DropdownMenuItem(value: 'diario', child: Text('Diario')), DropdownMenuItem(value: 'mensual', child: Text('Mensual'))], onChanged: (v) => sl(() => period = v!)), const SizedBox(height: 20), ElevatedButton(onPressed: () async { if (tc.text.isEmpty || ac.text.isEmpty) return; final amount = double.tryParse(ac.text); if (amount == null) return; final now = DateTime.now(); await ctx.read<GoalProvider>().add(GoalModel(title: tc.text, targetAmount: amount, period: period, startDate: '${now.year}-${now.month.toString().padLeft(2,'0')}-${now.day.toString().padLeft(2,'0')}', createdAt: now.toIso8601String())); if (ctx.mounted) Navigator.pop(ctx); }, child: const Text('Crear meta')), const SizedBox(height: 16)])))); }
}
class _GT extends StatelessWidget {
  final GoalModel goal;
  const _GT({required this.goal});
  @override
  Widget build(BuildContext context) => ListTile(leading: Container(padding: const EdgeInsets.all(6), decoration: BoxDecoration(color: AppColors.warning.withOpacity(0.15), borderRadius: BorderRadius.circular(8)), child: const Text('🎯', style: TextStyle(fontSize: 18))), title: Text(goal.title), subtitle: Text('\$${goal.targetAmount.toStringAsFixed(0)} · ${goal.period}'), trailing: IconButton(icon: const Icon(Icons.delete_outline_rounded, color: Colors.red), onPressed: () => context.read<GoalProvider>().delete(goal.id!)));
}
class _SH extends StatelessWidget {
  final String title;
  const _SH({required this.title});
  @override
  Widget build(BuildContext context) => Padding(padding: const EdgeInsets.fromLTRB(16, 20, 16, 4), child: Text(title.toUpperCase(), style: const TextStyle(color: AppColors.primary, fontSize: 11, fontWeight: FontWeight.w800, letterSpacing: 1.2)));
}
