import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/providers.dart';
import '../../core/constants/app_constants.dart';
import '../../models/models.dart';
class SavingsScreen extends StatelessWidget {
  const SavingsScreen({super.key});
  @override
  Widget build(BuildContext context) { final saving = context.watch<SavingProvider>(); final income = context.watch<IncomeProvider>(); final settings = context.watch<SettingsProvider>(); final suggested = saving.suggest(income.deliveryIncome, settings.deliveryPercentage); return Scaffold(appBar: AppBar(title: const Text('Ahorro')), floatingActionButton: FloatingActionButton.extended(onPressed: () => _dialog(context), backgroundColor: AppColors.saving, icon: const Icon(Icons.add), label: const Text('Registrar ahorro')), body: ListView(padding: const EdgeInsets.all(16), children: [Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(gradient: const LinearGradient(colors: [Color(0xFF4ECDC4), Color(0xFF44B5AF)], begin: Alignment.topLeft, end: Alignment.bottomRight), borderRadius: BorderRadius.circular(20)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('💰 Total ahorrado', style: TextStyle(color: Colors.white70, fontSize: 14)), const SizedBox(height: 8), Text('\$${saving.totalSaved.toStringAsFixed(0)}', style: const TextStyle(color: Colors.white, fontSize: 36, fontWeight: FontWeight.w800)), const SizedBox(height: 16), Container(padding: const EdgeInsets.all(12), decoration: BoxDecoration(color: Colors.white.withOpacity(0.2), borderRadius: BorderRadius.circular(10)), child: Row(children: [const Icon(Icons.lightbulb_rounded, color: Colors.white, size: 18), const SizedBox(width: 8), Expanded(child: Text('Sugerido (${settings.deliveryPercentage.toInt()}%): \$${suggested.toStringAsFixed(0)}', style: const TextStyle(color: Colors.white, fontSize: 13)))]))])), const SizedBox(height: 16), if (suggested > 0) OutlinedButton.icon(onPressed: () => _saveSuggested(context, suggested), icon: const Icon(Icons.auto_awesome_rounded), label: Text('Guardar sugerido: \$${suggested.toStringAsFixed(0)}'), style: OutlinedButton.styleFrom(foregroundColor: AppColors.saving, side: const BorderSide(color: AppColors.saving, width: 2), minimumSize: const Size(double.infinity, 52), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)))), const SizedBox(height: 24), if (saving.savings.isEmpty) const Center(child: Padding(padding: EdgeInsets.all(32), child: Column(children: [Text('🐷', style: TextStyle(fontSize: 48)), SizedBox(height: 12), Text('Sin ahorros registrados', style: TextStyle(fontWeight: FontWeight.w600))]))) else ...[Text('Historial', style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w700)), const SizedBox(height: 8), ...saving.savings.map((s) => _STile(saving: s))]])); }
  void _dialog(BuildContext context) { final c = TextEditingController(); final n = TextEditingController(); showModalBottomSheet(context: context, isScrollControlled: true, shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))), builder: (ctx) => Padding(padding: EdgeInsets.only(bottom: MediaQuery.of(ctx).viewInsets.bottom, left: 20, right: 20, top: 24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Registrar ahorro', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 16), TextField(controller: c, keyboardType: TextInputType.number, autofocus: true, decoration: const InputDecoration(labelText: 'Monto', prefixText: '\$ ')), const SizedBox(height: 12), TextField(controller: n, decoration: const InputDecoration(labelText: 'Nota (opcional)')), const SizedBox(height: 20), ElevatedButton(style: ElevatedButton.styleFrom(backgroundColor: AppColors.saving), onPressed: () async { final amount = double.tryParse(c.text); if (amount == null || amount <= 0) return; final now = DateTime.now(); await ctx.read<SavingProvider>().add(SavingModel(amount: amount, note: n.text.isEmpty ? null : n.text, type: 'manual', date: '${now.year}-${now.month.toString().padLeft(2,'0')}-${now.day.toString().padLeft(2,'0')}', createdAt: now.toIso8601String())); if (ctx.mounted) Navigator.pop(ctx); }, child: const Text('Guardar')), const SizedBox(height: 16)]))); }
  void _saveSuggested(BuildContext context, double suggested) async { final now = DateTime.now(); await context.read<SavingProvider>().add(SavingModel(amount: suggested, note: 'Ahorro automático', type: 'automatico', date: '${now.year}-${now.month.toString().padLeft(2,'0')}-${now.day.toString().padLeft(2,'0')}', createdAt: now.toIso8601String())); if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Guardado: \$${suggested.toStringAsFixed(0)} ✅'), backgroundColor: AppColors.saving)); }
}
class _STile extends StatelessWidget {
  final SavingModel saving;
  const _STile({required this.saving});
  @override
  Widget build(BuildContext context) { final dark = Theme.of(context).brightness == Brightness.dark; final isA = saving.type == 'automatico'; return Dismissible(key: Key('s_${saving.id}'), direction: DismissDirection.endToStart, background: Container(alignment: Alignment.centerRight, padding: const EdgeInsets.only(right: 16), decoration: BoxDecoration(color: Colors.red, borderRadius: BorderRadius.circular(12)), child: const Icon(Icons.delete_rounded, color: Colors.white)), onDismissed: (_) => context.read<SavingProvider>().delete(saving.id!), child: Container(margin: const EdgeInsets.only(bottom: 8), padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: dark ? const Color(0xFF16213E) : Colors.white, borderRadius: BorderRadius.circular(12), border: Border.all(color: AppColors.saving.withOpacity(0.2))), child: Row(children: [Container(padding: const EdgeInsets.all(10), decoration: BoxDecoration(color: AppColors.saving.withOpacity(0.15), borderRadius: BorderRadius.circular(10)), child: Icon(isA ? Icons.auto_awesome_rounded : Icons.savings_rounded, color: AppColors.saving, size: 20)), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(isA ? 'Ahorro automático' : 'Ahorro manual', style: const TextStyle(fontWeight: FontWeight.w600)), if (saving.note != null) Text(saving.note!, style: TextStyle(color: Colors.grey[600], fontSize: 12)), Text(saving.date, style: TextStyle(color: Colors.grey[500], fontSize: 11))])), Text('+\$${saving.amount.toStringAsFixed(0)}', style: const TextStyle(color: AppColors.saving, fontWeight: FontWeight.w800, fontSize: 16))]))); }
}
