import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'providers/providers.dart';
import 'views/home/home_screen.dart';
class DomiFinanceApp extends StatelessWidget {
  const DomiFinanceApp({super.key});
  @override
  Widget build(BuildContext context) => Consumer<SettingsProvider>(builder: (context, settings, _) => MaterialApp(title: 'DomiFinance', debugShowCheckedModeBanner: false, themeMode: settings.themeMode, theme: _light(), darkTheme: _dark(), home: const HomeScreen()));
  ThemeData _light() { const p = Color(0xFF00C896); return ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: p, brightness: Brightness.light, primary: p), textTheme: GoogleFonts.plusJakartaSansTextTheme(), appBarTheme: AppBarTheme(backgroundColor: Colors.white, foregroundColor: const Color(0xFF1A1A2E), elevation: 0, centerTitle: true, titleTextStyle: GoogleFonts.plusJakartaSans(color: const Color(0xFF1A1A2E), fontSize: 18, fontWeight: FontWeight.w700)), floatingActionButtonTheme: const FloatingActionButtonThemeData(backgroundColor: p, foregroundColor: Colors.white), elevatedButtonTheme: ElevatedButtonThemeData(style: ElevatedButton.styleFrom(backgroundColor: p, foregroundColor: Colors.white, minimumSize: const Size(double.infinity, 52), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)))), inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: const Color(0xFFF5F5F5), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none), focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: p, width: 2)), contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14)), cardTheme: CardThemeData(elevation: 0, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)), color: Colors.white), bottomNavigationBarTheme: const BottomNavigationBarThemeData(selectedItemColor: p, unselectedItemColor: Colors.grey, backgroundColor: Colors.white, type: BottomNavigationBarType.fixed, elevation: 8)); }
  ThemeData _dark() { const p = Color(0xFF00C896); const surface = Color(0xFF1A1A2E); const card = Color(0xFF16213E); return ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: p, brightness: Brightness.dark, primary: p, surface: surface), scaffoldBackgroundColor: surface, textTheme: GoogleFonts.plusJakartaSansTextTheme(ThemeData.dark().textTheme), appBarTheme: AppBarTheme(backgroundColor: surface, foregroundColor: Colors.white, elevation: 0, centerTitle: true, titleTextStyle: GoogleFonts.plusJakartaSans(color: Colors.white, fontSize: 18, fontWeight: FontWeight.w700)), floatingActionButtonTheme: const FloatingActionButtonThemeData(backgroundColor: p, foregroundColor: Colors.white), elevatedButtonTheme: ElevatedButtonThemeData(style: ElevatedButton.styleFrom(backgroundColor: p, foregroundColor: Colors.white, minimumSize: const Size(double.infinity, 52), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)))), inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: card, border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none), focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: p, width: 2))), cardTheme: CardThemeData(elevation: 0, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)), color: card), bottomNavigationBarTheme: const BottomNavigationBarThemeData(selectedItemColor: p, unselectedItemColor: Colors.grey, backgroundColor: surface, type: BottomNavigationBarType.fixed)); }
}
